name: Rust

on:
  push:
    branches: [ "development", "staging", "main" ]
  pull_request:
    branches: [ "development", "staging", "main" ]

env:
  CARGO_TERM_COLOR: always
  WORKING_DIR: ./

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ${{ env.WORKING_DIR }}
      run: cargo build --verbose

    - name: Run Rustfmt
      working-directory: ${{ env.WORKING_DIR }}
      run: cargo fmt --check

    - name: Run tests
      working-directory: ${{ env.WORKING_DIR }}
      run: cargo test --verbose
